import type { VerticalPack } from "./types";

/**
 * Loodgieter — eerste en enige live job-vertical. Let op: alles hieronder staat
 * in productie. Uitbreidingen zijn additief (nieuwe categorieën, velden, objecten
 * en catalogus); bestaande sleutels, de spoedregels en de AI-prompt zijn door
 * tests vastgelegd en veranderen hier niet.
 */
export const LOODGIETER_VERTICAL: VerticalPack = {
  id: "loodgieter",
  label: "Loodgieter",
  archetype: "job",
  live: true,
  // Loodgieterswerk aan woningen is 21%. Volgens de Belastingdienst geldt 9%
  // alleen voor isoleren, schilderen, stukadoren en behangen van woningen ouder
  // dan 2 jaar (en schoonmaken), dus nooit een sector-default. Dit staat op
  // 21/21 en de eigenaar kiest per regel een ander tarief waar dat echt geldt
  // (bijv. arbeid voor isolatie). Do NOT "fix" this back to 9%.
  vatRates: { treatment: 21, product: 21 },
  terms: {
    practitioner: "loodgieter",
    practitionerPlural: "monteurs",
    treatment: "klus",
    treatmentPlural: "klussen",
    establishment: "bedrijf",
    owner: "vakman",
    appointment: "afspraak",
  },
  // Leidingwerk gaat per meter of per punt (aansluitpunt), radiatoren per stuk.
  lineUnits: ["uur", "stuk", "m", "punt", "post", "dag", "m²"],
  hasHealthDataGuard: false,
  jobTitleExample: "Lekkage onder de gootsteen",
  brand: {
    name: "LoodgietersAssistent",
    domain: "loodgietersassistent.nl",
    siteUrl: "https://www.loodgietersassistent.nl",
    supportEmail: "support@loodgietersassistent.nl",
    tagline: "Nooit meer een gemiste noodoproep",
    description:
      "Het klus-CRM met AI-receptionist voor loodgietersbedrijven: telefoon en WhatsApp 24/7, klusadres en spoed direct vastgelegd, werkbon, offerte en factuur in één plek.",
    hosts: ["loodgietersassistent.nl", "www.loodgietersassistent.nl"],
    dashboardTitle: "Mijn LoodgietersAssistent",
  },
  // Diep petrol: water en techniek, duidelijk anders dan de sage van de kapper
  // en het blauw van de schilder; contrast getoetst (wit op primary ≥ 7:1).
  theme: {
    primary: "#0f5c6e",
    onPrimary: "#ffffff",
    primaryContainer: "#7fb6c4",
    onPrimaryContainer: "#032a33",
    primaryFixed: "#c4ebf5",
    primaryFixedDim: "#a3ced9",
    onPrimaryFixed: "#021f26",
    onPrimaryFixedVariant: "#0a4453",
    inversePrimary: "#a3ced9",
  },
  features: {
    jobs: true,
    quotes: true,
    assets: true,
    contracts: true,
    // Voor/na-foto's per klus: bewijs bij lekkage- en schadedossiers en bij verzekeraars.
    photoTimeline: true,
    treatmentCards: false,
    healthRecords: false,
    webshop: false,
    doubleBooking: false,
    loyalty: false,
  },
  pricing: {
    essential: {
      name: "Essential Assistent",
      tagline: "Voor zelfstandige loodgieters en installateurs.",
      audience: "Zelfstandig",
      valueLine: "Terugverdiend met 1 gered spoedgeval per maand.",
      features: [
        "AI neemt telefoon én WhatsApp op, 24/7 — ook als je onder een gootsteen ligt",
        "Legt klusadres, probleem en foto's direct vast als klus in je CRM",
        "Herkent spoed (lekkage, gaslucht, geen verwarming in de kou) en geeft eerst veiligheidstips",
        "Klanten met meerdere adressen en een volledige klushistorie",
        "Planbord per monteur: spoed staat bovenaan",
        "Werkbon met checklist en voor/na-foto's op je telefoon, met opleverhandtekening en garantie",
        "Automatische afspraakherinneringen en review-verzoeken",
      ],
    },
    pro: {
      name: "Pro Assistent",
      tagline: "Voor installatiebedrijven met meerdere monteurs.",
      audience: "Meerdere monteurs",
      valueLine: "Sneller offreren, sneller betaald, terugkerende omzet.",
      features: [
        "Alles uit Essential",
        "Offertes die de klant online accepteert; facturen met IBAN en automatische betalingsherinneringen",
        "Installatiepaspoort per adres: merk, type, serienummer, garantie en het volgende onderhoud, ook als printbaar document",
        "Onderhoudscontracten: de klus en de klantherinnering ontstaan vanzelf",
        "Aanbetaling bij inplannen — minder afzeggingen op het laatste moment",
        "Kan een gesprek bij gaslucht of een gesprongen leiding direct doorzetten naar de monteur van dienst",
        "WhatsApp-berichtkosten zitten al in de prijs, geen aparte factuur",
      ],
    },
    elite: {
      name: "Elite Cockpit",
      tagline: "Voor grotere installatiebedrijven.",
      audience: "Groot bedrijf",
      valueLine: "Eén cockpit voor al je monteurs en vestigingen.",
      features: [
        "Alles uit Pro",
        "Beheer meerdere vestigingen vanuit één cockpit",
        "Maandelijks rapport: precies wat de AI je heeft opgeleverd",
      ],
    },
  },
  agent: {
    tools: [
      "check_availability",
      "find_appointments",
      "book_appointment",
      "reschedule_appointment",
      "cancel_appointment",
      "register_job",
      "escalate_to_staff",
    ],
    prompt: {
      spoedRule:
        "een acuut probleem (water dat blijft lopen of door het plafond komt, gaslucht, geen warm water of verwarming bij kou, veiligheidsrisico) behandel je als spoed. Geef eerst korte veiligheidstips (bijv. hoofdkraan afsluiten, stroom uit bij water bij stopcontacten). Bij gaslucht: ramen open, geen vuur of lichtschakelaars aanraken, het pand verlaten en het gasstoringsnummer 0800-9009 bellen; bij acuut gevaar 112.",
      hazardExamples: "gaslek, ernstige waterschade",
      quoteExamples: "een nieuwe ketel of badkamer",
      photoRule:
        "gebruik die om in te schatten welke {treatment} en hoeveel tijd nodig is, en noem dat kort in je antwoord. Bij een mogelijk gevaarlijke situatie (gaslek, ernstige waterschade) altijd escalate_to_staff gebruiken in plaats van zelf gerust te stellen. De foto wordt automatisch bij de klus gevoegd.",
      scene: "onderweg of onder een gootsteen ligt",
      urgencyHint: "spoed = acuut (water/gas/geen verwarming in de kou/veiligheid); anders normaal",
      photoSubjects: "een lekkage, leiding of cv-ketel",
    },
  },
  integrations: ["whatsapp", "phone", "moneybird", "eboekhouden", "exact_online", "google_calendar"],
  jobFields: [
    {
      key: "woningOuderDan2Jaar",
      label: "Woning ouder dan 2 jaar?",
      type: "select",
      options: ["Onbekend", "Ja", "Nee"],
      hint: "Het verlaagde tarief (9%) geldt alleen voor bepaalde werken aan woningen ouder dan 2 jaar, zoals isoleren. Voor loodgieterswerk is het doorgaans 21%. Controleer het bij de Belastingdienst.",
    },
    { key: "bouwjaar", label: "Bouwjaar woning", type: "number", placeholder: "1985" },
    {
      key: "hoofdkraanBereikbaar",
      label: "Hoofdkraan bereikbaar?",
      type: "select",
      options: ["Onbekend", "Ja", "Nee"],
      categories: ["lekkage", "sanitair", "badkamer"],
    },
    { key: "foutcode", label: "Foutcode ketel", type: "text", placeholder: "bv. F.22", categories: ["cv_storing", "cv_onderhoud"] },
    {
      key: "toestelType",
      label: "Type toestel",
      type: "select",
      options: ["CV-ketel", "Hybride", "Warmtepomp", "Boiler", "Geiser", "Anders"],
      categories: ["cv_storing", "cv_onderhoud", "cv_installatie"],
    },
    { key: "aantalRadiatoren", label: "Aantal radiatoren", type: "number", categories: ["cv_installatie", "verwarming"] },
    { key: "toestelMerk", label: "Merk toestel", type: "text", placeholder: "bv. Remeha, Vaillant, Intergas", categories: ["cv_storing", "cv_onderhoud", "cv_installatie", "boiler"] },
    { key: "toestelBouwjaar", label: "Bouwjaar toestel", type: "number", placeholder: "2012", hint: "Bepaalt of onderdelen nog leverbaar zijn en of vervangen slimmer is.", categories: ["cv_storing", "cv_onderhoud", "cv_installatie", "boiler"] },
    {
      key: "lekkageLocatie",
      label: "Waar is het lek?",
      type: "select",
      options: ["Onbekend", "Plafond", "Muur", "Vloer", "Onder aanrecht of wastafel", "Bij de cv-ketel", "Buiten of in de kruipruimte"],
      categories: ["lekkage"],
    },
    {
      key: "verstoppingLocatie",
      label: "Waar is de verstopping?",
      type: "select",
      options: ["Onbekend", "Gootsteen", "Wastafel of douche", "Toilet", "Buitenriool of put", "Meerdere afvoeren"],
      hint: "Meerdere afvoeren tegelijk wijst vaak op een probleem in het hoofdriool.",
      categories: ["verstopping", "riool"],
    },
    { key: "badkamerOppervlak", label: "Oppervlak badkamer", type: "number", unit: "m²", placeholder: "6", categories: ["badkamer"] },
    {
      key: "netbeheerderGewaarschuwd",
      label: "Netbeheerder gewaarschuwd?",
      type: "select",
      options: ["Onbekend", "Ja", "Nee"],
      hint: "Bij gaslucht buiten of bij de meter hoort de netbeheerder het gasstoringsnummer 0800-9009 te bellen.",
      categories: ["gaslucht"],
    },
    {
      key: "gasluchtLocatie",
      label: "Waar ruikt het naar gas?",
      type: "select",
      options: ["Onbekend", "Binnen in de woning", "Bij de cv-ketel of gastoestel", "Bij de gasmeter", "Buiten"],
      categories: ["gaslucht"],
    },
    // Meetwaarden bij onderhoud (rookgasanalyse); invulling door de monteur ter plaatse.
    { key: "meetCo", label: "CO in rookgas", type: "number", unit: "ppm", placeholder: "40", categories: ["cv_onderhoud"] },
    { key: "meetCo2", label: "CO₂ in rookgas", type: "number", unit: "%", placeholder: "9", categories: ["cv_onderhoud"] },
    { key: "meetRookgastemperatuur", label: "Rookgastemperatuur", type: "number", unit: "°C", placeholder: "60", categories: ["cv_onderhoud"] },
    { key: "meetWaterdruk", label: "Waterdruk installatie", type: "number", unit: "bar", placeholder: "1.5", categories: ["cv_onderhoud", "cv_storing", "verwarming"] },
    {
      key: "meetUitkomst",
      label: "Uitkomst controle",
      type: "select",
      options: ["Onbekend", "Goedgekeurd", "Goedgekeurd met advies", "Afgekeurd, herstel nodig"],
      categories: ["cv_onderhoud"],
    },
    {
      key: "warmtepompType",
      label: "Type warmtepomp",
      type: "select",
      options: ["Onbekend", "Hybride (met cv-ketel)", "Lucht-water (all-electric)", "Bodem-water", "Lucht-lucht (airco)"],
      categories: ["warmtepomp"],
    },
    { key: "woonoppervlak", label: "Woonoppervlak", type: "number", unit: "m²", placeholder: "120", categories: ["warmtepomp", "cv_installatie"] },
    {
      key: "isolatieNiveau",
      label: "Isolatie woning",
      type: "select",
      options: ["Onbekend", "Slecht of geen", "Redelijk (bijv. spouw- en dakisolatie)", "Goed (ook vloer en HR++ glas)"],
      hint: "Bepaalt of een warmtepomp zonder extra isolatie kan, of dat een hybride beter past.",
      categories: ["warmtepomp"],
    },
    {
      key: "afgifteSysteem",
      label: "Afgifte in de woning",
      type: "select",
      options: ["Onbekend", "Vloerverwarming", "Lage-temperatuurradiatoren", "Standaard radiatoren"],
      categories: ["warmtepomp"],
    },
    {
      key: "groepenkastRuimte",
      label: "Ruimte in de groepenkast / aansluiting",
      type: "select",
      options: ["Onbekend", "Voldoende", "Uitbreiding nodig"],
      hint: "Een elektrische warmtepomp heeft een eigen groep nodig; vaak is een elektricien nodig voor uitbreiding.",
      categories: ["warmtepomp"],
    },
    {
      key: "fgasCertificaat",
      label: "Werk aan koudemiddelcircuit?",
      type: "select",
      options: ["Nee", "Ja, F-gassencertificaat aanwezig", "Ja, via gecertificeerde partner"],
      hint: "Werkzaamheden aan het koudemiddelcircuit vereisen een geldig F-gassencertificaat — controleer de actuele regels.",
      categories: ["warmtepomp"],
    },
  ],
  marketing: {
    navLinks: [
      { href: "/#functies", label: "Functies" },
      { href: "/#hoe-het-werkt", label: "Hoe het werkt" },
      { href: "/prijzen", label: "Prijzen" },
      { href: "/blog", label: "Blog" },
      { href: "/kennisbank", label: "Kennisbank" },
      { href: "/help", label: "Hulp" },
      { href: "/contact", label: "Contact" },
    ],
    cta: { href: "/scan", label: "Gratis scan" },
    footerBlurb:
      "Het klus-CRM met AI-receptionist voor loodgietersbedrijven: geen spoedoproep meer missen, van aanvraag tot betaalde factuur op één plek.",
    logoIcon: "plumbing",
    landing: {
      badge: "Voor loodgieters en installatiebedrijven",
      headline: "Nooit meer een gemiste noodoproep.",
      sub: "Terwijl jij onder een lekkende leiding ligt, rinkelt de telefoon. LoodgietersAssistent neemt 24/7 op via telefoon en WhatsApp, legt klusadres en spoed vast en zet alles klaar in je klus-CRM: van aanvraag tot betaalde factuur.",
      appPreview: {
        company: "De Vries Installatie",
        date: "Maandag 28 september",
        greeting: "Goedemorgen, Mark",
        summary: "3 klussen bezig · 5 nog in te plannen",
        urgentTitle: "2 spoedklussen wachten op je",
        urgent: [
          { title: "Lekkende cv-ketel", who: "Mevrouw Bakker", status: "Onderweg", statusTone: "progress" },
          { title: "Gaslucht in de meterkast", who: "Familie Yilmaz", status: "Nieuw", statusTone: "new" },
        ],
        tabs: [
          { icon: "dashboard", label: "Overzicht" },
          { icon: "construction", label: "Klussen" },
          { icon: "calendar_view_week", label: "Planbord" },
          { icon: "group", label: "Klanten" },
        ],
      },
      chat: {
        title: "WhatsApp — LoodgietersAssistent",
        messages: [
          { from: "customer", text: "Hoi, mijn cv-ketel lekt en het water staat al op de vloer. Kunnen jullie vandaag nog komen?" },
          {
            from: "ai",
            text: "Dat klinkt als spoed. Kun je de hoofdkraan afsluiten? Stuur me je adres, dan leg ik het direct vast en waarschuw ik de monteur van dienst.",
          },
        ],
      },
      stats: [
        { icon: "call", value: "Nooit gemist", label: "Ook 's avonds en in het weekend." },
        { icon: "emergency", value: "Spoed direct gemeld", label: "Jij krijgt meteen een mail en WhatsApp." },
        { icon: "receipt_long", value: "Van klus tot factuur", label: "Alles in één systeem." },
      ],
      steps: [
        {
          title: "Jij stelt je bedrijf in",
          body: "Diensten, tarieven, monteurs en wat als spoed geldt. We geven je een startcatalogus mee; jij past hem aan.",
        },
        {
          title: "De AI neemt de oproepen aan",
          body: "Telefoon en WhatsApp: naam, klusadres, probleem en spoed worden vastgelegd. Foto's van de klant komen bij de klus.",
        },
        {
          title: "Jij plant, werkt en factureert",
          body: "Zet de klus op het planbord, maak een offerte of werkbon, laat de klant online accepteren en stuur de factuur.",
        },
      ],
      features: [
        { icon: "smart_toy", title: "AI-receptionist 24/7", body: "Neemt telefoon en WhatsApp op, herkent spoed en legt het klusadres vast. Bij twijfel of gevaar verbindt hij door." },
        { icon: "emergency", title: "Spoed-triage", body: "Lekkage, gaslucht, geen verwarming: spoed krijgt veiligheidstips, een spoedmarkering en een directe melding aan jou." },
        { icon: "group", title: "Klant-CRM met adressen", body: "Klanten met meerdere adressen, toegangsinfo, contactpersoon ter plaatse en de volledige klushistorie." },
        { icon: "calendar_view_week", title: "Planbord per monteur", body: "Wie is waar en wanneer. Spoed bovenaan, overlappende klussen worden gemarkeerd." },
        { icon: "checklist", title: "Werkbon op je telefoon", body: "Checklist per soort klus, rookgasmetingen (CO, CO₂) bij onderhoud, foto's voor en na, werkverslag en opleverhandtekening met garantie." },
        { icon: "request_quote", title: "Offertes en facturen", body: "Offerte online accepteren, één klik naar factuur, IBAN op de factuur en automatische betalingsherinneringen." },
        { icon: "build_circle", title: "Installatiepaspoort", body: "Merk, type, serienummer en garantie van elke ketel, boiler of warmtepomp, met het volgende onderhoud in beeld. Print het als document voor de klant." },
        { icon: "event_repeat", title: "Onderhoudscontracten", body: "Elke beurt ontstaat vanzelf als klus en de klant krijgt automatisch bericht. Terugkerende omzet zonder handwerk." },
      ],
      faq: [
        {
          q: "Werkt dit ook zonder planningssoftware?",
          a: "Ja. Klussen, planning, offertes en facturen zitten in LoodgietersAssistent zelf — je hoeft niets te koppelen om te starten.",
        },
        {
          q: "Wat gebeurt er bij een spoedgeval?",
          a: "De AI geeft eerst veiligheidstips (bijvoorbeeld hoofdkraan dicht, bij gaslucht ramen open en 112 of het gasstoringsnummer), legt de klus vast als spoed en waarschuwt jou direct per mail en WhatsApp.",
        },
        {
          q: "Kan ik mijn eigen tarieven en categorieën instellen?",
          a: "Ja. Je begint met een voorbeeldcatalogus (ontstopping, lekkage, cv-onderhoud, spoedtarief) en past prijzen, duur en teksten aan.",
        },
        {
          q: "Hoe zit het met btw en facturen?",
          a: "Facturen bevatten de wettelijk verplichte gegevens (KvK, btw-nummer, factuurnummer, btw per tarief). Het btw-tarief kies je per regel — 21%, 9% of 0%. Loodgieterswerk is doorgaans 21%; het verlaagde tarief geldt alleen voor specifieke werken zoals isoleren, dus de keuze blijft bij jou.",
        },
        {
          q: "Wat is een installatiepaspoort?",
          a: "Per adres leg je merk, type, serienummer, garantie en het volgende onderhoud van elke ketel, boiler of warmtepomp vast. Zo weet je bij een storing meteen wat er hangt, en komt elk onderhoud op tijd terug.",
        },
        {
          q: "Kan ik ook warmtepompklussen vastleggen?",
          a: "Ja. Warmtepomp en hybride hebben een eigen soort klus met een checklist en velden voor type, isolatie, afgifte en groepenkast. Het toestel komt in het installatiepaspoort, met onderhoudsinterval en garantie.",
        },
        {
          q: "Kan ik meetwaarden van een cv-onderhoud vastleggen?",
          a: "Ja. Bij cv-onderhoud leg je CO, CO₂, rookgastemperatuur, waterdruk en de uitkomst van de controle vast. Ze staan op de werkbon en bij de klus.",
        },
        {
          q: "Kan een klant meerdere adressen hebben?",
          a: "Ja. Klanten met meerdere adressen, toegangsinfo, contactpersoon ter plaatse en de volledige klushistorie worden ondersteund.",
        },
        {
          q: "Zit er een looptijd of overage op de AI?",
          a: "Nee. Je betaalt een vast bedrag per maand, opzegbaar per maand, zonder kosten per gesprek of per minuut.",
        },
      ],
      ctaTitle: "Klaar om geen spoedklus meer te missen?",
      ctaBody: "Plan een gratis kennismaking — binnen 48 uur werkend, geen creditcard nodig.",
    },
  },
  nav: [
    { key: "overview" },
    { key: "jobs" },
    { key: "planner" },
    { key: "customers" },
    { key: "billing" },
    { key: "maintenance" },
    { key: "ai", label: "AI-Receptie" },
    { key: "conversations" },
    { key: "escalations", label: "Spoed & doorverbinden" },
    { key: "practice", label: "Diensten & team" },
    { key: "reports" },
    { key: "retention", label: "Reviews & terugkeer" },
    { key: "noshow", label: "Annulering & voorrijkosten" },
    { key: "integrations" },
    { key: "subscription" },
    { key: "guide" },
  ],
  onboarding: [
    { key: "services", label: "Diensten en tarieven (start met de voorbeeldcatalogus)" },
    { key: "business" },
    { key: "team", label: "Monteurs toegevoegd" },
    { key: "phone", label: "Telefonische receptie actief (zodat geen spoedoproep verloren gaat)" },
    { key: "whatsapp" },
    { key: "firstJob" },
  ],
  jobCategories: [
    {
      key: "lekkage",
      label: "Lekkage",
      urgent: true,
      estimatedMinutes: 90,
      keywords: ["lek", "lekkage", "druppelt", "waterschade", "natte plek", "water door het plafond", "leiding gesprongen", "bevroren leiding", "vorstschade", "water uit de muur"],
      checklist: [
        "Hoofdkraan afgesloten / water uit",
        "Lekbron gelokaliseerd",
        "Lek verholpen",
        "Druk- en dichtheidscontrole gedaan",
        "Foto's voor/na gemaakt",
        "Opgeruimd en klant geïnstrueerd",
      ],
    },
    {
      key: "gaslucht",
      label: "Gaslucht / gasstoring",
      urgent: true,
      estimatedMinutes: 60,
      keywords: ["gaslucht", "gaslek", "gas ruiken", "gasgeur"],
      checklist: [
        "Veiligheid ter plaatse gecontroleerd (ventilatie, geen ontstekingsbronnen)",
        "Gasleiding/aansluitingen gecontroleerd",
        "Lekzoekspray of meter gebruikt",
        "Eventueel netbeheerder ingeschakeld",
        "Bevindingen vastgelegd",
      ],
    },
    {
      key: "verstopping",
      label: "Verstopping / ontstopping",
      urgent: false,
      estimatedMinutes: 60,
      keywords: ["verstopt", "ontstoppen", "afvoer", "gootsteen loopt niet door", "toilet verstopt", "stinkt"],
      checklist: [
        "Locatie verstopping bepaald",
        "Ontstopt (spiraal/hogedruk)",
        "Doorstroming getest",
        "Eventueel camera-inspectie aangeboden",
        "Opgeruimd en klant geïnstrueerd",
      ],
    },
    {
      key: "cv_storing",
      label: "CV-storing / geen warm water",
      urgent: false,
      estimatedMinutes: 75,
      keywords: ["cv", "ketel", "storing", "geen warm water", "geen verwarming", "foutcode", "cv-ketel", "radiator wordt niet warm"],
      checklist: [
        "Foutcode/symptoom genoteerd",
        "Ketel en druk gecontroleerd",
        "Oorzaak vastgesteld en verholpen",
        "Ketel getest onder belasting",
        "Klant geïnstrueerd",
      ],
    },
    {
      key: "cv_onderhoud",
      label: "CV-onderhoud",
      urgent: false,
      estimatedMinutes: 60,
      keywords: ["onderhoud", "jaarlijks onderhoud", "cv onderhoud", "keuring", "servicebeurt"],
      checklist: [
        "Ketel schoongemaakt",
        "Brander en warmtewisselaar gecontroleerd",
        "Rookgasanalyse gedaan, CO en CO₂ vastgelegd in de klusvelden",
        "Waterdruk gecontroleerd",
        "Onderhoudsdatum in installatiepaspoort bijgewerkt",
      ],
    },
    {
      key: "cv_installatie",
      label: "CV-ketel vervangen / installatie",
      urgent: false,
      estimatedMinutes: 300,
      keywords: ["nieuwe ketel", "ketel vervangen", "installeren", "nieuwe cv"],
      checklist: [
        "Oude installatie afgetapt en gedemonteerd",
        "Nieuwe installatie geplaatst en aangesloten",
        "Gas-/rookgasafvoer gecontroleerd",
        "Ingeregeld en getest",
        "Installatiepaspoort en garantie ingevuld",
        "Klant geïnstrueerd",
      ],
    },
    {
      key: "riool",
      label: "Riool / camera-inspectie",
      urgent: false,
      estimatedMinutes: 120,
      keywords: ["riool", "rioolcamera", "camera inspectie", "rioolreparatie", "wortels in riool", "put verstopt", "stankoverlast", "riool stinkt"],
      checklist: [
        "Klacht en locatie besproken met klant",
        "Riool ontstopt of gespoeld",
        "Camera-inspectie gedaan en beelden bewaard",
        "Oorzaak vastgesteld (wortels, verzakking, vet)",
        "Vervolgadvies en offerte voor herstel besproken",
      ],
    },
    {
      key: "warmtepomp",
      label: "Warmtepomp / hybride",
      urgent: false,
      estimatedMinutes: 480,
      keywords: ["warmtepomp", "hybride warmtepomp", "all-electric", "van het gas af", "aardgasvrij", "lucht-water", "isde", "subsidie warmtepomp"],
      checklist: [
        "Woning opgenomen (isolatie, afgifte, woonoppervlak)",
        "Warmteverliesberekening gedaan of afgesproken",
        "Elektrische aansluiting en groepenkast beoordeeld",
        "Binnen- en buitenunit geplaatst en aangesloten",
        "Koudemiddelcircuit door gecertificeerd monteur gedaan",
        "Stooklijn ingeregeld en getest",
        "Installatiepaspoort en garantie ingevuld",
        "Klant geïnstrueerd en documentatie overhandigd",
      ],
    },
    {
      key: "boiler",
      label: "Boiler / geiser",
      urgent: false,
      estimatedMinutes: 150,
      keywords: ["boiler", "geiser", "warmwatertoestel", "boiler lekt", "boiler vervangen", "geiser vervangen", "warm water op"],
      checklist: [
        "Type toestel en aansluitingen bekeken",
        "Water afgesloten en toestel afgetapt",
        "Nieuw toestel geplaatst en aangesloten",
        "Veiligheidsgroep en afvoer gecontroleerd",
        "Getest en klant geïnstrueerd",
        "Installatiepaspoort bijgewerkt",
      ],
    },
    {
      key: "verwarming",
      label: "Radiatoren / vloerverwarming",
      urgent: false,
      estimatedMinutes: 180,
      keywords: ["radiator", "radiatoren", "vloerverwarming", "ontluchten", "koude radiator", "radiator lekt", "thermostaat", "inregelen"],
      checklist: [
        "Symptoom vastgesteld (koud, lucht, lek)",
        "Installatie ontlucht en waterdruk gecontroleerd",
        "Radiator, kraan of verdeler hersteld of vervangen",
        "Installatie ingeregeld en getest",
        "Klant geïnstrueerd",
      ],
    },
    {
      key: "sanitair",
      label: "Sanitair / kraan / toilet",
      urgent: false,
      estimatedMinutes: 90,
      keywords: ["kraan", "toilet", "wastafel", "douche", "sanitair", "stortbak", "mengkraan"],
      checklist: [
        "Water afgesloten",
        "Onderdeel gedemonteerd/vervangen",
        "Aansluitingen dichtheid getest",
        "Opgeruimd",
      ],
    },
    {
      key: "badkamer",
      label: "Badkamer / renovatie",
      urgent: false,
      estimatedMinutes: 480,
      keywords: ["badkamer", "verbouwen", "renovatie", "nieuwe badkamer", "leidingwerk"],
      checklist: [
        "Opname en maatvoering gedaan",
        "Leidingwerk aangelegd",
        "Sanitair geplaatst",
        "Druk- en dichtheidsproef gedaan",
        "Oplevering met klant",
      ],
    },
    {
      key: "overig",
      label: "Overig",
      urgent: false,
      estimatedMinutes: 60,
      keywords: [],
      checklist: ["Werkzaamheden uitgevoerd", "Opgeruimd en klant geïnstrueerd"],
    },
  ],
  assetKinds: [
    { key: "cv_ketel", label: "CV-ketel", icon: "heat_pump", serviceIntervalMonths: 12 },
    { key: "warmtepomp", label: "Warmtepomp", icon: "ac_unit", serviceIntervalMonths: 12 },
    { key: "boiler", label: "Boiler / warmwatertoestel", icon: "water_heater", serviceIntervalMonths: 24 },
    { key: "geiser", label: "Geiser", icon: "local_fire_department", serviceIntervalMonths: 12 },
    { key: "vloerverwarming", label: "Vloerverwarming", icon: "layers", serviceIntervalMonths: null },
    { key: "radiatoren", label: "Radiatoren", icon: "thermostat", serviceIntervalMonths: null },
    { key: "waterleiding", label: "Waterleiding en kranen", icon: "water_drop", serviceIntervalMonths: null },
    { key: "pomp", label: "Pomp / drukverhoging", icon: "water_pump", serviceIntervalMonths: 12 },
    { key: "waterontharder", label: "Waterontharder", icon: "water_drop", serviceIntervalMonths: 12 },
    { key: "ventilatie", label: "Mechanische ventilatie", icon: "air", serviceIntervalMonths: null },
    { key: "sanitair", label: "Sanitair", icon: "bathtub", serviceIntervalMonths: null },
    { key: "riolering", label: "Riolering / afvoer", icon: "plumbing", serviceIntervalMonths: null },
    { key: "overig", label: "Overig", icon: "build", serviceIntervalMonths: null },
  ],
  // Voorbeeldprijzen — de eigenaar past ze aan; bedoeld als startpunt.
  serviceTemplates: [
    { name: "Voorrijkosten", category: "overig", durationMinutes: 0, priceCents: 3500, vatRatePercent: 21, description: "Voorrijkosten per bezoek." },
    { name: "Ontstopping afvoer", category: "verstopping", durationMinutes: 60, priceCents: 9500, vatRatePercent: 21, description: "Ontstoppen van gootsteen, wastafel, douche of toilet." },
    { name: "Lekkage opsporen en verhelpen", category: "lekkage", durationMinutes: 90, priceCents: 12500, vatRatePercent: 21, description: "Lekkage lokaliseren en herstellen (excl. materiaal)." },
    { name: "CV-onderhoud", category: "cv_onderhoud", durationMinutes: 60, priceCents: 8900, vatRatePercent: 21, description: "Jaarlijks onderhoud aan de cv-ketel." },
    { name: "CV-storing", category: "cv_storing", durationMinutes: 75, priceCents: 9500, vatRatePercent: 21, description: "Storing diagnosticeren en verhelpen (excl. onderdelen)." },
    { name: "Camera-inspectie riool", category: "riool", durationMinutes: 90, priceCents: 14500, vatRatePercent: 21, description: "Riool inspecteren met camera, incl. beelden voor de klant." },
    { name: "Ontstopping hoofdriool / buitenput", category: "riool", durationMinutes: 90, priceCents: 17500, vatRatePercent: 21, description: "Ontstoppen met hogedruk of spiraal." },
    { name: "Radiator ontluchten en waterdruk bijvullen", category: "verwarming", durationMinutes: 45, priceCents: 7500, vatRatePercent: 21, description: "Installatie ontluchten en waterdruk op peil brengen." },
    { name: "Mengkraan vervangen", category: "sanitair", durationMinutes: 60, priceCents: 9500, vatRatePercent: 21, description: "Kraan demonteren en vervangen (excl. kraan)." },
    { name: "Toilet of stortbak vervangen", category: "sanitair", durationMinutes: 120, priceCents: 15000, vatRatePercent: 21, description: "Toilet of stortbak vervangen (excl. materiaal)." },
    { name: "Boiler plaatsen", category: "boiler", durationMinutes: 150, priceCents: 22500, vatRatePercent: 21, description: "Boiler of geiser plaatsen en aansluiten (excl. toestel)." },
    { name: "Rookgasanalyse en CO-meting", category: "cv_onderhoud", durationMinutes: 30, priceCents: 4500, vatRatePercent: 21, description: "Meting van CO, CO₂ en rookgastemperatuur; waarden worden vastgelegd op de werkbon." },
    { name: "CV-ketel vervangen (arbeid)", category: "cv_installatie", durationMinutes: 300, priceCents: 55000, vatRatePercent: 21, description: "Oude ketel verwijderen, nieuwe plaatsen, aansluiten en inregelen (excl. toestel en materiaal)." },
    { name: "Warmtepomp: opname en advies", category: "warmtepomp", durationMinutes: 90, priceCents: 15000, vatRatePercent: 21, description: "Opname ter plaatse: isolatie, afgifte, aansluiting en advies over hybride of all-electric." },
    { name: "Hybride warmtepomp plaatsen (arbeid)", category: "warmtepomp", durationMinutes: 480, priceCents: 105000, vatRatePercent: 21, description: "Plaatsen en aansluiten naast de bestaande cv-ketel, inregelen (excl. toestel en eventueel elektrawerk)." },
    { name: "Installatie inregelen", category: "verwarming", durationMinutes: 120, priceCents: 15000, vatRatePercent: 21, description: "Radiatoren en stooklijn inregelen voor een gelijkmatige en zuinige verwarming." },
    { name: "Waterontharder onderhoud", category: "boiler", durationMinutes: 60, priceCents: 9500, vatRatePercent: 21, description: "Jaarlijkse controle en onderhoud van de waterontharder (excl. zout en onderdelen)." },
    { name: "Loodgieter per uur", category: "overig", durationMinutes: 60, priceCents: 7500, vatRatePercent: 21, description: "Uurtarief loodgieter (excl. materiaal)." },
    { name: "Spoedtarief buiten kantoortijd", category: "lekkage", durationMinutes: 60, priceCents: 15500, vatRatePercent: 21, description: "Spoedklus in avond, nacht of weekend." },
  ],
  // Complete offerteregels per typische klus. Toestel en materiaal staan op €0 als
  // invulplek: de vakman kent zijn inkoop en marge, wij verzinnen die niet.
  quotePackages: [
    {
      name: "CV-ketel vervangen",
      description: "Voorrijkosten, toestel, materiaal en arbeid voor een complete ketelvervanging.",
      lines: [
        { kind: "travel", description: "Voorrijkosten", quantity: 1, unit: "stuk", priceCents: 3500 },
        { kind: "material", description: "Materiaal: cv-ketel (merk en type invullen)", quantity: 1, unit: "stuk", priceCents: 0 },
        { kind: "material", description: "Materiaal: rookgasafvoer, aansluitmateriaal en overig", quantity: 1, unit: "post", priceCents: 0 },
        { kind: "labor", description: "Arbeid: oude ketel verwijderen, nieuwe plaatsen, aansluiten en inregelen", quantity: 1, unit: "post", priceCents: 55000 },
        { kind: "labor", description: "Rookgasanalyse en CO-meting bij oplevering", quantity: 1, unit: "stuk", priceCents: 4500 },
      ],
    },
    {
      name: "Boiler of geiser plaatsen",
      description: "Toestel plaatsen en aansluiten, inclusief veiligheidsgroep en afvoer.",
      lines: [
        { kind: "travel", description: "Voorrijkosten", quantity: 1, unit: "stuk", priceCents: 3500 },
        { kind: "material", description: "Materiaal: boiler of geiser (merk en type invullen)", quantity: 1, unit: "stuk", priceCents: 0 },
        { kind: "material", description: "Materiaal: veiligheidsgroep, leidingwerk en overig", quantity: 1, unit: "post", priceCents: 0 },
        { kind: "labor", description: "Arbeid: toestel plaatsen, aansluiten en testen", quantity: 1, unit: "post", priceCents: 22500 },
      ],
    },
    {
      name: "Hybride warmtepomp plaatsen",
      description: "Opname, plaatsing en inregelen naast de bestaande cv-ketel. Elektrawerk apart opnemen.",
      lines: [
        { kind: "labor", description: "Opname ter plaatse en advies", quantity: 1, unit: "stuk", priceCents: 15000 },
        { kind: "material", description: "Materiaal: hybride warmtepomp (merk en type invullen)", quantity: 1, unit: "stuk", priceCents: 0 },
        { kind: "material", description: "Materiaal: leidingwerk, aansluitmateriaal en overig", quantity: 1, unit: "post", priceCents: 0 },
        { kind: "labor", description: "Arbeid: plaatsen, aansluiten en inregelen (excl. elektrawerk)", quantity: 1, unit: "post", priceCents: 105000 },
        { kind: "other", description: "Elektrawerk (groepenkast en aansluiting) door elektricien", quantity: 1, unit: "post", priceCents: 0 },
      ],
    },
    {
      name: "Badkamer: leidingwerk en sanitair",
      description: "Leidingwerk per punt, sanitair plaatsen en druk- en dichtheidsproef.",
      lines: [
        { kind: "labor", description: "Opname en maatvoering", quantity: 1, unit: "stuk", priceCents: 0 },
        { kind: "labor", description: "Leidingwerk aanleggen per aansluitpunt", quantity: 1, unit: "punt", priceCents: 0 },
        { kind: "material", description: "Materiaal: leidingen en fittingen", quantity: 1, unit: "post", priceCents: 0 },
        { kind: "labor", description: "Sanitair plaatsen en aansluiten", quantity: 1, unit: "post", priceCents: 0 },
        { kind: "labor", description: "Druk- en dichtheidsproef en oplevering", quantity: 1, unit: "stuk", priceCents: 0 },
      ],
    },
    {
      name: "Jaarlijks cv-onderhoud",
      description: "Onderhoudsbeurt inclusief rookgasanalyse.",
      lines: [
        { kind: "labor", description: "CV-onderhoud: reinigen en controleren", quantity: 1, unit: "stuk", priceCents: 8900 },
        { kind: "labor", description: "Rookgasanalyse en CO-meting", quantity: 1, unit: "stuk", priceCents: 4500 },
      ],
    },
  ],
  messages: {
    reminder: ({ salonName, serviceType, date, time }) =>
      `Hoi! Een herinnering van ${salonName}: onze monteur komt ${date} rond ${time} bij je langs voor ${serviceType}. ` +
      `Kun je niet thuis zijn? Laat het ons tijdig weten via WhatsApp. Tot dan! 👷`,
    review: ({ salonName, reviewLink }) =>
      `Hoi! Bedankt dat we bij je langs mochten komen. Was je tevreden over ${salonName}? Een review helpt ons enorm: ${reviewLink}`,
    retention: ({ salonName, firstName }) =>
      `Hoi ${firstName}! ${salonName} hier. Is alles nog in orde bij je thuis? Heb je iets waar we naar kunnen kijken, stuur gerust een berichtje 👷`,
    maintenanceDue: ({ salonName, firstName, assetLabel, dueDate }) =>
      `Hoi ${firstName}! ${salonName} hier: het onderhoud aan je ${assetLabel} staat gepland voor ${dueDate}. Zullen we een dag en tijd afspreken? Stuur ons gerust een berichtje.`,
    greetingFallback: "vakman",
  },
  content: {
    audience: "eigenaren van loodgietersbedrijven en installatiebedrijven",
    blogSystemPrompt: `Je bent een Nederlandse SEO-contentspecialist voor loodgieters- en installatiebedrijven.
Schrijf praktische, autoritaire en nuchtere blogartikelen (B2B, voor eigenaren van loodgietersbedrijven).
Gebruik Markdown met ## en ### tussenkoppen, korte alinea's en bullets.
Noem concrete voorbeelden uit de praktijk (gemiste spoedoproepen, offertes, werkbonnen, onderhoudscontracten, planning).
Vermijd overdrijving en holle marketingtaal. Schrijf in het Nederlands.`,
    blogTopicPlaceholder: "bijv. Gemiste spoedoproepen voorkomen als loodgieter",
    blogKeywordPlaceholder: "loodgieter software, spoedklus, offerte loodgieter, onderhoudscontract",
    blogSuggestions: [
      "Gemiste spoedoproepen voorkomen als loodgieter",
      "Sneller offreren: van aanvraag naar geaccepteerde offerte",
      "Onderhoudscontracten voor cv-ketels: zo bouw je terugkerende omzet op",
      "Werkbonnen op je telefoon in plaats van papier",
      "Lokaal gevonden worden als loodgieter in jouw regio",
      "Een storingsdienst buiten kantoortijd zonder zelf op te nemen",
      "Camera-inspectie riool: van klacht naar herstelofferte",
    ],
    blogMetaTitle: "Blog — Tips voor loodgieters en installatiebedrijven",
    blogMetaDescription:
      "Praktische tips over spoedklussen, offertes, onderhoudscontracten en het runnen van een loodgietersbedrijf.",
    blogHeading: "Tips voor loodgieters en installateurs",
    blogSubheading: "Praktische inzichten over spoedklussen, offertes, planning en terugkerende omzet.",
    postCta: {
      title: "Geen spoedklus meer missen?",
      body: "Ontdek wat LoodgietersAssistent voor jouw bedrijf kan betekenen.",
      href: "/contact",
      label: "Plan een gratis kennismaking",
    },
    kennisbankCategories: {
      Spoed: "Spoed & storingen",
      Offertes: "Offertes & facturen",
      Planning: "Planning & werkbonnen",
      Onderhoud: "Onderhoud & contracten",
      Vakkennis: "Vakkennis",
      Marketing: "Gevonden worden",
    },
    kennisbankHeading: "Kennisbank voor loodgieters",
    kennisbankTitle: "Kennisbank — Praktijktips voor loodgieters",
    kennisbankDescription:
      "Gratis kennisbank-artikelen over spoedklussen, offertes en werkbonnen, onderhoudscontracten en het runnen van een loodgietersbedrijf.",
    kennisbankIntro:
      "Praktijktips voor loodgieters en installateurs: van spoedklussen en offertes tot onderhoudscontracten en planning.",
  },
};
